# Defines any custom property or configuration for the current problem.
# The config values can be retrieved at runtime, for example inside the experiment
# See https://mork-optimization.readthedocs.io/en/latest/features/config/ for more details
custom:
  # Configuration for Gurobi solver (repetitions must be established to 1 in line 45 below)
  gurobi-time-limit: 3600
  gurobi-model-file: 'model-gurobi-new-constraints.py'
  # Configuration for final VNS algorithm
  mh-time-limit-in-seconds: 120
  algorithm-description: 'algorithm=gvns constructive=grasprg alpha=value alphaValue=0.4 maxKpct=0.44 lsOrder=collapseFirst'

instances:

  # Loads all instances in RAM before starting each experiment.
  # Can be disabled for example in problems where instances are huge in order to save some RAM.
  # Warning: Disabling it reverts instance solve order to instance name (lexicographically)
  preload: true

  path:
    # Default instance path for all experiments, can be overridden.
    default: 'instances'

    # Override default instance path only for the experiment declared in file PreliminarExperiment.java
    # If an experiment does not have a specific path the default will be used. Example:
    # PreliminarExperiment: './instances/preliminar'

  # Instance selection
  preliminar-percentage: 0.25
  preliminar-output-path: 'instances/selected'
  for-selection: 'instances/all'

solver:
  # Global random seed to ensure reproducibility
  seed: 1234

  # Random generator provider, see RandomType enum for a full list of available implementations
  random-type: default

  # Experiments to be executed.
  #experiments: 'ExactModelExperiment'
  #experiments: 'HexalyExperiment'
  experiments: 'CustomAlgorithmExperiment'

  # How many times should each experiment be repeated. Recommended a minimum of 30
  repetitions: 30

  # Use parallel executor DISABLE IF THE ALGORITHM IS ALREADY PARALLELIZED
  # Valid Values: true, false
  parallelExecutor: true

  # Number of workers to use if parallelExecutor is enabled
  # any number between 1 and MAX_INT, or -1 to automatically decide at runtime (available threads / 2)
  nWorkers: -1

  # Execute benchmark before starting solver? False to skip benchmark.
  benchmark: true



  ### FROM THIS POINT ON, DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING ###

  # Autoconfig properties
  ## Tree depth when using automatic configuration
  tree-depth: 4
  ## For each solution generated by any algorithm, ignore this millis in the area calculation.
  ## WARNING: Any algorithm that does not report an o.f value before this limit is reached is considered invalid
  ignore-initial-millis: 10000
  ## Area will be measured in interval [ignoreInitialMillis, ignoreInitialMillis+intervalDurationMillis]
  interval-duration-millis: 50000
  # End autoconfig properties

  # Enable or disable metrics tracking. Force enabled if using autoconfig.
  metrics: true

# Enable irace integration? Check IRACE Wiki section before enabling
irace:
  enabled: true

  # False: (EXPERIMENTAL) use GraalVM implementation, does not need R installed locally
  # True: (RECOMMENDED) Use shell to execute R scripts, R / Rscript need to be locally installed and in path
  shell: true

  # Maximum number of algorithm executions
  maxExperiments: 10000

# Event system integrations/configuration
event:
  # Stop webserver after all work is done?
  # If true, app will stop after all experiments finish executing, and front end will stop loading. (DEFAULT)
  # If false, webserver will keep executing, and front will be available until manually stopped by the user.
  webserver:
    stopOnExecutionEnd: true

  # Enable message notifications to any given user on experiment end. See
  telegram:
    # If false bot is completely disabled
    enabled: false
    # Token returned by @BotFather
    token: ''
    # Chat where we will send notifications
    chatId: ''

# Experiment execution DOES NOT (usually) END if an uncontrolled exception is propagated
# The error is logged, and we try to keep solving
errors:
  # Write exceptions and errors with their context to disk?
  errorsToFile: true

  # Path where all errors or exceptions encountered during experiment execution will be exported
  folder: 'errors'

# Set default server port (change if there is multiple Mork instances running)
server:
  port : 8080

# Advanced configuration, do not change unless you know what you are doing!
advanced:
  # Block Java API methods
  block:
    # Collections.shuffle(RandomManager.getRandom()) should be used instead of Collections.shuffle()
    block-collections-shuffle: false
    # Block Math.random(), use RandomManager.getRandom().nextDouble()
    block-math-random: false